#!/usr/bin/python3
def raise_exception():
    a = 15
    b = "6"
    result = a + b
    return result
